### ISSUE TITLE
"Torrorist" sticker?

### ISSUE THREAD

**Issue by thedod** [shiromarieke/shiro_stickers#1]
If you still have the graphics of "I am a torrorist", please upload it :pray:.
Thanks.

**Comment by shiromarieke** [comment]
I've never made a "I am a torrorist" sticker. I made a "we have onions" stickers which you can find here: https://github.com/shiromarieke/shiro_stickers/blob/master/we_have_onions.jpg
I believe what you are referring to is the "I am a torrorist" jacket/tote bags/t-shirts design, which I don't have as a file. It's basically that sticker with the line "I am a torrorist" line above, in the same light green color, in some typewriter font - probably as simple as courier.
Hope that's helpful info! (And I'm happy to share an .svg of the "we have onions", if you want).
